name: 'Push directory to another repository'
description: 'Useful to push files to another repository to be used, for example, via github pages'
inputs:
  destination-github-username:
    description: 'Name of the destination username/organization'
    required: true
  user-email:
    description: 'Email for the git commit'
    required: true
  destination-branch:
    description: 'Destination branch'
    required: true
runs:
  using: 'composite'
  steps: 
    - run: 'sh entrypoint.sh ${{ inputs.destination-github-username }} ${{ inputs.user-email }} ${{ inputs.destination-branch }}'
      shell: bash
branding:
  icon: 'git-commit'
  color: 'green'
